### ISSUE TITLE
Conditionally include the /graphql route

### ISSUE THREAD

**Issue by zachfeldman** [nebulab/solidus_graphql_api-1#209]
**Desired Behavior**

For those testing out GraphQL but not yet ready to have it in production, it would be great to conditionally include the route.

**Comment by zachfeldman** [comment]
@waiting-for-dev thanks for getting this merged!!

Any change of a 0.3.1 release so we can point to that instead of a specific SHA on GitHub within our project? :smiley: 

Enjoy your weekend :wave:

**Comment by waiting-for-dev** [comment]
@zachfeldman, all yours! :point_right: https://rubygems.org/gems/solidus_graphql_api/versions/0.3.1 :slightly_smiling_face: 

Happy weekend! :clap:
