### ISSUE TITLE
Currency Type

### ISSUE THREAD

**Issue by ChristianRimondi** [nebulab/solidus_graphql_api-1#53]
- create the `CurrencyType` like the `Money::Currency`;
- add the `currencies`(or `available_currencies`?) to the `StoreType` (`Spree::Config.available_currencies`);
- use the new `CurrencyType` in the `PriceType` instead of the old `currency` and `currency_symbol` fields (`Spree::Price#display_amount.currency`)

**Comment by rainerdema** [comment]
Closed by #62
